# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a8ceef6dcb028070de784712a51160f9584e14c5c3d569d1bbf017c1e1deff4aa2d9fac0deb8b7198251342f5777f4205b2fa350d409bfc7dcddb2cc94094e6b

test:
  secret_key_base: 14f629c532a89805b3b23bc7cd41c10e6523959ae27e20ba869d7e749826d9c5f39299ed8eff3f0a873f45dd6cd0744a848f5f60302fa1d9f305ed248d56ac5d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
