THESAURUS = {   '(MRI) Magnetic Resonance': 'procedure that uses magnetic waves to take a picture of various parts of',
    'Absorb': 'Take up fluids',
    'BID': 'twice a day',
    'CT': 'computer enhanced X-ray; special type of x-ray',
    'CT scan': 'computer enhanced X-ray; special type of x-ray',
    'CT scanned': 'computer enhanced X-ray; special type of x-ray',
    'CT scanning': 'computer enhanced X-raying; special type of x-raying',
    'CT scans': 'computer enhanced X-rays; special type of x-rays',
    'ECG': 'picture and measurement of the hearts rhythm',
    'EEG': 'measurement of electrical activity of the brain',
    'EKG': 'picture and measurement of the hearts rhythm',
    'Holter monitor': 'a machine',
    'Holter monitored': 'a machined',
    'Holter monitoring': 'a machining',
    'Imaging': 'the body (radiation is not used)',
    'MEDICAL TERM': 'LAY TERMINOLOGY',
    'MUGA': 'procedure using a special camera to look at the heart after radioactive dye has been put into it through one of the veins',
    'NG tube (nasogastric)': 'a flexible plastic tube that is passed through the nose or mouth and into the stomach',
    'NG tubed (nasogastric)': 'a flexible plastic tube that is passed through the nose or mouth and into the stomach',
    'NG tubing (nasogastric)': 'flexible plastic tubing that is passed through the nose or mouth and into the stomach',
    'PET (Positron Emission': 'special camera that uses radiation to look at the structure and functioning',
    'QD': 'every day',
    'QID': 'four times a day',
    'T-lymphocytes': 'type of white blood cells involved in immune reactions',
    'TID': 'three times a day',
    'Term': 'Definition',
    'Tomography)': 'of parts of the body',
    'abdomen': 'belly',
    'abdomens': 'bellies',
    'ablation': 'remove',
    'ablations': 'removes',
    'abstain': 'avoid',
    'abstained': 'avoided',
    'abstaining': 'avoiding',
    'acuities': 'Clearnesses',
    'acuity': 'Clearness',
    'acute': 'short-term; sudden onset',
    'acutes': 'short-term; sudden onsets',
    'adenopathies': 'swollen glandss',
    'adenopathy': 'swollen glands',
    'adjuvant': 'Helpful',
    'adjuvants': 'Helpfuls',
    'adverse effect': 'side effect',
    'adverse effected': 'sided effected',
    'adverse effecting': 'siding effecting',
    'allergic reaction': 'rash',
    'allergic reactions': 'rashes',
    'alopecia': 'hair loss',
    'alopecias': 'hair losses',
    'ambulate': 'walk',
    'ambulated': 'walked',
    'ambulating': 'walking',
    'amnesia': 'loss of memory; inability to remember',
    'amnesias': 'losses of memory; inability to remember',
    'analgesic': 'pain relieving medication',
    'analgesics': 'pain relieving medications',
    'anaphylaxes': 'a severes',
    'anaphylaxis': 'a severe',
    'anemia': 'low red blood cell count',
    'anemias': 'low red blood cell counts',
    'anesthetize': 'to numb; put to sleep',
    'anesthetized': 'to numb; put to slept',
    'anesthetizing': 'to numb; putting to sleeping',
    'angina': 'pain from not enough blood to the heart',
    'anginas': 'pains from not enough blood to the heart',
    'anorexia': 'loss of appetite',
    'anorexias': 'losses of appetite',
    'antecubital': 'Inside the elbow',
    'antibiotic (antimicrobial)': 'drug that kills germs',
    'antibodies': 'natural chemicals in the body that fight infection',
    'anticonvulsant': 'drug used to prevent seizures',
    'anticonvulsants': 'drug used to prevent seizuress',
    'antilipidemic': 'drug that decreases the level of fat in the blood',
    'antiretroviral': 'drug that inhibits viruses',
    'antitussive': 'drug that relieves coughing',
    'antitussives': 'drug that relieves coughings',
    'anus': 'rectum',
    'anuss': 'rectums',
    'arrhythmiaa': 'change from the normal heartbeat',
    'arteries': 'blood vessels',
    'artery': 'blood vessel',
    'arthralgia': 'joint pain',
    'arthralgias': 'joint pains',
    'aspiration': 'inhale into the lungs; to suck in; or removal of fluid through tube or needle',
    'aspirations': 'inhales into the lungs; to suck in; or removal of fluid through tube or needle',
    'assess': 'to learn about',
    'assessed': 'to learnt about',
    'assessing': 'to learning about',
    'asthenia': 'loss of energy; weakness',
    'asthenias': 'losses of energy; weakness',
    'asthma': 'lung disease associated with tightening of the air passages',
    'asthmas': 'lung disease associated with tightening of the air passagess',
    'asymptomatic': 'without symptoms',
    'ataxia': 'unsteady movement',
    'ataxias': 'unsteady movements',
    'axilla': 'armpit',
    'axillas': 'armpits',
    'bacteria': 'germs',
    'bacterias': 'germss',
    'benign': 'not cancerous; without serious consequences',
    'bioavailability': 'the extent to which a drug becomes available to the body',
    'biopsies': 'the removal and examination of a small part of tissue or organs',
    'biopsy': 'the removal and examination of a small part of tissue or organ',
    'blood profile': 'series of blood tests',
    'blood profiles': 'series of blood tests',
    'blooded profile': 'series of blooded tests',
    'blooding profile': 'series of blooding tests',
    'bolus': 'given all at once',
    'boluss': 'given all at onces',
    'bone density': 'bone thickness; hardness of bone',
    'boned density': 'boned thickness; hardness of boned',
    'boning density': 'boning thickness; hardness of boning',
    'bradycardia': 'slow heart rate',
    'bradycardias': 'slow heart rates',
    'bronchospasm': 'difficulty breathing because the airways have narrowed',
    'bronchospasms': 'difficulty breathing because the airways have narroweds',
    'carcinogenic': 'can cause cancer',
    'carcinoma': 'a type of cancer',
    'carcinomata': 'a type of cancers',
    'cardiac': 'heart; involving the heart',
    'cardiac catheterization': 'a procedure in which a small tube (catheter) is inserted through blood vessels in the groin and into the heart that uses highlighting fluid to look at the blood vessels in the heart',
    'cardioversion': 'a procedure that uses electricity to simulate the heart and make it return to its normal rhythm',
    'catheter': 'flexible plastic tube that is inserted into the ( )',
    'catheters': 'flexible plastic tube that is inserted into the ( )s',
    'central nervous system': 'the brain and spinal cord',
    'central nervous systems': 'the brain and spinal cords',
    'cerebral trauma': 'damage to the brain',
    'cessation': 'stopping',
    'cessations': 'stoppings',
    'chemotherapies': 'treatments of disease with chemical agents',
    'chemotherapy': 'treatment of disease with chemical agents',
    'chronic': 'continues for a long time; long-term',
    'clinical': 'medical care',
    'clinical trial': 'an experiment in humans',
    'clinical trials': 'an experiment in humanss',
    'clinically significant': 'of major importance for treating or evaluating patients',
    'coerced': 'pressured; forced',
    'cognitive status': 'levels of awareness and thinking',
    'colon': 'large intestines; bowel',
    'colonoscopies': 'procedures to look at the large intestine that uses a special camera at the',
    'colonoscopy': 'procedure to look at the large intestine that uses a special camera at the end of a long tube that is inserted in the rectum',
    'colons': 'large intestines; bowels',
    'coma': 'unconscious state',
    'comas': 'unconscious states',
    'computed tomography': 'computer enhanced X-ray; special type of x-ray',
    'computed tomography scan': 'computer enhanced X-ray; special type of x-ray',
    'computed tomography scanned': 'computer enhanced X-ray; special type of x-ray',
    'computed tomography scanning': 'computer enhanced X-raying; special type of x-raying',
    'computed tomography scans': 'computer enhanced X-rays; special type of x-rays',
    'confidentiality will not be compromised': 'other people will not find out',
    'congenital': 'occurring prior to birth',
    'conjunctivitis': 'irritation and redness in the membrane covering the eye',
    'consent': 'agreement',
    'consented': 'agreement',
    'consenting': 'agreement',
    'consents': 'agreements',
    'contrast material': 'a fluid that is given into the vein or an area of the body to highlight the blood vessels or body area under x-ray examination',
    'contrasting material': 'a fluid that is given into the vein or an area of the body to highlight the blood vessels or body area under x-ray examination',
    'convulsions': 'seizures',
    'coronaries': 'hearts; involving the hearts',
    'coronary': 'heart; involving the heart',
    'creatinine clearance': 'a test of kidney function',
    'culture': 'a test for the presence of germs',
    'cultures': 'a test for the presence of germs',
    'cumulative': 'total sum (of events',
    'cutaneous': 'of the skin',
    'de novo': 'new',
    'defecate': 'bowel movement; to pass stools',
    'defecated': 'bowel movement; passed stools',
    'defecating': 'passing stools',
    'defibrillation': 'a procedure that uses electricity to stimulate the heart and make it return to its normal rhythm',
    'defibrillations': 'a procedure that uses electricity to stimulate the heart and make it return to its normal rhythm',
    'dermatologic': 'of the skin',
    'deteriorate': 'to get worse; to lose function',
    'deteriorated': 'to get worse; lost function',
    'deteriorating': 'to get worse; losing function',
    'diastolic blood pressure': 'the blood pressure when the heart rests between beats; the bottom number of a blood pressure reading',
    'diplopia': 'double vision',
    'diplopias': 'double visions',
    'distal': 'away from the center of the body',
    'distensions': 'bloated; swollen; inflated',
    'diuretic': 'drug that causes an increase in urination',
    'diuretics': 'drugs that causes an increase in urination',
    'double-blind': 'neither you nor your doctor will know what medicine you are taking',
    'duodenum': 'beginning of the small intestine that is attached to the stomach',
    'duodenums': 'beginnings of the small intestine that is attached to the stomach',
    'dysfunction': 'not functioning properly',
    'dysfunctions': 'not functioning properly',
    'dyspepsia': 'gas; upset stomach',
    'dyspepsias': 'gas; upset stomaches',
    'dysplasia': 'abnormal cells',
    'dysplasias': 'abnormal cellss',
    'dyspnea': 'hard to breathe; short of breath',
    'dyspneas': 'hards to breathe; short of breath',
    'dysrhythmia': 'a change from the normal heartbeat',
    'echocardiogram': 'procedure that uses sound waves to look at the heart; using sound waves to take pictures of the heart chambers and measure its pumping strength',
    'echocardiograms': 'procedures that use sound waves to look at the heart; using sound waves to take pictures of the heart chambers and measure its pumping strength',
    'edema': 'swelling',
    'edemata': 'swellings',
    'efficacies': 'effectiveness; usefulnesses',
    'efficacy': 'effectiveness; usefulness',
    'electrocardiogram': 'picture and measurement of the hearts rhythm',
    'electrocardiograms': 'picture and measurements of the hearts rhythm',
    'electrode': 'wire',
    'electrodes': 'wires',
    'electrolyte imbalance': 'imbalance of salts or chemicals in the blood',
    'electrophysiology studied': 'heart rhythm studied',
    'electrophysiology study': 'heart rhythm study',
    'electrophysiology studying': 'heart rhythm studying',
    'elevation of liver function tests': 'evidence of liver or kidney damage',
    'elevation of liver functioned tests': 'evidenced of liver or kidney damaged',
    'elevation of liver functioning tests': 'evidencing of liver or kidney damaging',
    'elucidate': 'to make clear; to determine; to find out',
    'elucidated': 'to made clear; to determine; to find outed',
    'elucidating': 'to making clear; to determine; to find outing',
    'embryo': 'unborn baby',
    'embryos': 'unborn babies',
    'emeses': 'vomitings',
    'emesis': 'vomiting',
    'empiric': 'based on experience',
    'endoscopic exam': 'exam of an internal part of the body with a lighted tube',
    'enema': 'medication given through the rectum that cleans out the bowel',
    'enemata': 'medication given through the rectum that cleans out the bowels',
    'enteral': 'by way of the intestines',
    'enzyme abnormality': 'blood test result that suggests abnormal organ function or injured cells',
    'epidural': 'outside the spinal cord',
    'epidurals': 'outside the spinal cords',
    'eradicating': 'getting rid of',
    'exclusion criteria': 'reasons for not being included',
    'excreted': 'made; given off; put off',
    'external': 'outside of the body',
    'externals': 'outsides of the body',
    'extravasate': 'to leak outside of a blood vessel',
    'extravasated': 'to leaked outside of a blooded vessel',
    'extravasating': 'to leaking outside of a blooding vessel',
    'fast': 'do not eat or drink',
    'fasted': 'done not eaten or drunk',
    'fasting': 'doing not eating or drinking',
    'fasts': 'do not eat or drinks',
    'fatigue': 'tire',
    'fatigued': 'tired',
    'fatigues': 'tires',
    'fatiguing': 'tiring',
    'fetus': 'unborn baby',
    'fetuss': 'unborn babies',
    'fibrillation': 'irregular beat of the heart or other muscle',
    'fibrillations': 'irregular beat of the heart or other muscles',
    'fibrous': 'Having many fibers',
    'flatulence': 'gas passed through the anus/rectum',
    'flatulences': 'gas passed through the anus/rectums',
    'flushing': 'to become red in the face or other part of the body because of rush of blood to the skin; blushing of the skin',
    'fracture': 'break',
    'fractured': 'broke',
    'fractures': 'breaks',
    'fracturing': 'breaking',
    'gastric': 'stomach',
    'gastrointestinal': 'stomach and intestines',
    'gestational': 'pertaining to pregnancy',
    'glucose': 'sugar',
    'hematocrit': 'amount of red blood cells in the blood',
    'hematocrits': 'amounts of red blood cells in the blood',
    'hematoma': 'a bruise; bleeding into the body tissue around a blood vessel',
    'hematomas': 'a bruise; bleeding into the body tissue around a blood vessel',
    'hemodynamic measurement': 'test to measure blood flow',
    'hemolyses': 'breakdowns in red blood cells',
    'hemolysis': 'breakdown in red blood cells',
    'heparin lock': 'Needle placed with blood thinner to keep blood from clotting inside the needle or tubing',
    'heparin locked': 'Needle placed with blood thinner to keep blood from clotting inside the needle or tubing',
    'heparin locking': 'Needle placed with blood thinner to keep blood from clotting inside the needle or tubing',
    'hepatic': 'liver',
    'hepatics': 'livers',
    'hepatitis': 'inflammation of the liver',
    'hepatoma': 'cancer or tumor of the liver',
    'hepatomas': 'cancer or tumor of the livers',
    'heritable disease': 'a disease which can be passed to children resulting in damage to future children',
    'histopathologic': 'pertaining to disease of body tissues or cells',
    'history positive': 'in past medical history; that you have ever had',
    'hyerkalemia': 'high blood potassium level',
    'hypercalcemia': 'high blood calcium level',
    'hypercalcemias': 'high blood calcium levels',
    'hypernatremia': 'high blood sodium level',
    'hypernatremias': 'high blood sodium levels',
    'hypertension': 'high blood pressure',
    'hypertensions': 'high blood pressures',
    'hypocalcemia': 'low blood calcium level',
    'hypocalcemias': 'low blood calcium levels',
    'hypokalemia': 'low blood potassium level',
    'hypokalemias': 'low blood potassium levels',
    'hyponatremia': 'low blood sodium level',
    'hyponatremias': 'low blood sodium levels',
    'hypotension': 'low blood pressure',
    'hypotensions': 'low blood pressures',
    'hypoxia': 'low oxygen level in the blood',
    'hypoxias': 'low oxygen level in the bloods',
    'hysterectomies': 'removals of the womb',
    'hysterectomy': 'removal of the womb',
    'iatrogenic': 'caused by a physician or by treatment',
    'idiopathic': 'of unknown cause',
    'immobilization': 'unable to move',
    'immobilizations': 'unables to move',
    'immunological': "relating to the body's ability to fight infection",
    'immunosuppressive': 'drug which suppresses the body\xe2\x80\x99s immune response',
    'immunosuppressives': 'drug which suppresses the body\xe2\x80\x99s immune responses',
    'immunotherapies': 'drugs to help the body\xe2\x80\x99s immune system',
    'immunotherapy': 'drug to help the body\xe2\x80\x99s immune system',
    'impaired function': 'abnormal function',
    'impaired functioned': 'abnormal functioned',
    'impaired functioning': 'abnormal functioning',
    'implantation': 'operation to place a device inside the body',
    'implantations': 'operations to place a device inside the body',
    'incision': 'cut',
    'incisions': 'cuts',
    'indicated': 'suggested; necessary',
    'induce': 'cause',
    'induced': 'caused',
    'inducing': 'causing',
    'induction phase': 'beginning phase or stage of treatment',
    'induction phased': 'beginning phased or staged of treatment',
    'induction phasing': 'beginning phasing or staging of treatment',
    'induration': 'hardening',
    'indurations': 'hardenings',
    'indwelling': 'remaining in a given location',
    'inert': "not active; substance that doesn't affect you",
    'infarct': 'Death of tissue because of lack of blood supply',
    'infarcts': 'Deaths of tissue because of lack of blood supply',
    'infectious disease': 'disease transmitted from person to person',
    'infectious diseases': 'disease transmitted from people to people',
    'inflammation': 'swelling',
    'inflammations': 'swellings',
    'inflation': 'to put air in',
    'inflations': 'to put air ins',
    'infused': 'to drip in; to put in',
    'ingest': 'swallow; eat or drink',
    'ingested': 'swallow; eaten or drunk',
    'ingesting': 'swallow; eating or drinking',
    'inject': 'to put into by way of a needle or other device',
    'injected': 'to put into by way of a needled or other device',
    'injecting': 'to putting into by way of a needling or other device',
    'insomnia': 'unable to sleep',
    'insomnias': 'unables to sleep',
    'instilled': 'put into; drip into',
    'intensities': 'degree; amounts',
    'intensity': 'degree; amount',
    'interferon': 'agent that acts against viruses',
    'interferons': 'agent that acts against virusess',
    'intermittent': 'occurring repeatedly; alternately stopping and starting',
    'intramuscular injection': 'to put into the muscle with a needle',
    'intramuscular injections': 'to put into the muscle with a needles',
    'intraperitoneal': 'into the abdominal cavity',
    'intrathecal': 'into the spinal fluid',
    'intravenous': 'in the blood vessel',
    'intravenous infusion': 'to drip into the blood vessel through a plastic tube and needle',
    'intravesical': 'in the bladder',
    'intubate': 'the placement of a tube into the airway',
    'intubated': 'the placement of a tubed into the airway',
    'intubating': 'the placement of a tubing into the airway',
    'invasive procedure': 'puncture',
    'ischemia': 'decreased oxygen in a tissue (usually because of decreased blood flow)',
    'ischemias': 'decreased oxygen in a tissue (usually because of decreased blood flow)s',
    'isolated': 'to separate; to close off',
    'lactating': 'making breast milk',
    'laporatomy': 'Incision in the abdominal wall to allow a physician to look at the organs',
    'lesion': 'site of the injury; site of the disease',
    'lesions': 'sites of the injury; sites of the disease',
    'lethargies': 'Sleepinesses',
    'lethargy': 'Sleepiness',
    'leukocyte': 'blood cells that fight infection',
    'leukocytes': 'blood cells that fight infections',
    'leukopenia': 'low white blood cell count',
    'leukopenias': 'low white blood cell counts',
    'libido': 'sexual desire; sex drive',
    'libidoes': 'sexual desire; sex drives',
    'local anesthetic': 'medicine to numb an area of the body',
    'local anesthetics': 'medicines to numb an area of the body',
    'localized': 'restricted to one area',
    'lumbar puncture': 'spinal tap; a needle inserted between the bones of the spine to put in a drug or take a sample of fluid',
    'lumbar punctured': 'spinal tapped; a needle inserted between the bones of the spine to put in a drug or take a sample of fluid',
    'lumbar punctures': 'spinal taps; needles inserted between the bones of the spine to put in some drug or take a sample of fluid',
    'lumbar puncturing': 'spinal tapping; inserting needles between the bones of the spine to put in a drug or take a sample of fluid',
    'lumbosacral': 'lower back',
    'lymphangiographies': 'x-rays of the lymph nodes or tissues after injection of dye in lymph vessels',
    'lymphangiography': 'an x-ray of the lymph nodes or tissues after injection of dye in lymph vessels',
    'lymphocyte': 'a type of white blood cell',
    'lymphocytes': 'a type of white blood cells',
    'lymphoma': 'a cancer of the lymph nodes or tissues',
    'lymphomata': 'a cancer of the lymph nodes or tissues',
    'maintenance dose': 'the usual daily dose',
    'maintenance dosed': 'the usual daily dosed',
    'maintenance dosing': 'the usual daily dosing',
    'malaise': 'a vague feeling of discomfort',
    'malaises': 'a vague feeling of discomforts',
    'malignancies': 'tumor; cancers',
    'malignancy': 'tumor; cancer',
    'manifested': 'showed',
    'medullobastoma': 'type of brain tumor',
    'meningitis': 'infection or irritation around the brain',
    'metabolism': 'process by which food is used to supply energy for the body; the energy the body uses when it works; the way the body breaks down food or a drug',
    'metabolisms': 'processes by which food is used to supply energy for the body; the energy the body uses when it works; the way the body breaks down food or a drug',
    'metastasize': 'spread',
    'metastasized': 'spread',
    'metastasizing': 'spreading',
    'monitor': 'check on; keep track of; watch carefully',
    'monitored': 'checked on; kept tracked of; watched carefully',
    'monitoring': 'checking on; keeping tracking of; watching carefully',
    'monitors': 'check on; keep track of; watch carefullies',
    'morbidities': 'undesired result or complication; serious diseases',
    'morbidity': 'undesired result or complication; serious disease',
    'mortalities': 'Death or death rates',
    'mortality': 'Death or death rate',
    'mucosa': 'the lining inside the ( )',
    'mucosas': 'the lining inside the ( )s',
    'myalgia': 'muscle aches',
    'myalgias': 'muscle achess',
    'myocardial infarction': 'heart attack',
    'myocardial infarctions': 'heart attacks',
    'nasal': 'nose',
    'nasal congestion': 'stuffiness of the nose',
    'nasals': 'noses',
    'nasogastric tube': 'tube from the nose to the stomach',
    'nasogastric tubed': 'tubed from the nosed to the stomached',
    'nasogastric tubing': 'tubing from the nosing to the stomaching',
    'nausea': 'feel sick to the stomach',
    'nauseas': 'feel sick to the stomaches',
    'necroses': 'deaths of tissue',
    'necrosis': 'death of tissue',
    'neoplasia': 'tumor',
    'neoplasias': 'tumors',
    'neuroblastoma': 'cancer of nerve tissue',
    'neuroblastomas': 'cancers of nerve tissue',
    'neurological': 'pertaining to the nervous system',
    'neurological exam': 'test of brain',
    'neutropenia': 'Decrease in the main part of the white blood cells',
    'neutropenias': 'Decreases in the main part of the white blood cells',
    'new indication': 'new use',
    'non-invasive': 'not breaking',
    'nosocomial pneumonia': 'pneumonia acquired in the hospital',
    'occlusion': 'Closing; obstruction',
    'occlusions': 'Closing; obstructions',
    'occult blood test': 'a test for small amounts of blood in the stool',
    'occulted blooded tested': 'a tested for small amounts of blooded in the stooled',
    'occulting blooding testing': 'a testing for small amounts of blooding in the stooling',
    'oncologies': 'the study of tumors or cancers',
    'oncology': 'the study of tumors or cancer',
    'ophthalmic': 'pertaining to the eye',
    'optimum, optimal': 'best',
    'oral': 'by mouth',
    'orals': 'by mouths',
    'orthopedic': 'pertaining to the bones',
    'osteoarthritis': 'bone and joint pain',
    'osteopetroses': 'bones disorder characterized by dense bones',
    'osteopetrosis': 'bone disorder characterized by dense bone',
    'osteoporoses': 'bones disorder characterized by loss of bones',
    'osteoporosis': 'bone disorder characterized by loss of bone',
    'ovaries': 'female sex glands; female organs which release eggs',
    'over-the-counter drugs': "medications that you can buy without a doctor's prescription",
    'overnight fast': 'do not eat or drink after ( ) P.M.',
    'overnight fasted': 'done not eaten or drunk after ( ) P.M.',
    'overnight fasting': 'doing not eating or drinking after ( ) P.M.',
    'palpitations': 'irregular heart beats that you can feel',
    'parenteral': 'administration by injection',
    'paresthesia': 'tingling in the ( )',
    'paresthesias': 'tinglings in the ( )',
    'partial seizure': 'seizure',
    'patencies': 'conditions of being open',
    'patency': 'condition of being open',
    'pathogeneses': 'the initial cause of a diseases',
    'pathogenesis': 'the initial cause of a disease',
    'perception': 'view',
    'perceptions': 'views',
    'percutaneous': 'through the skin',
    'perforation': 'puncture',
    'perforations': 'punctures',
    'peripheral': 'not central',
    'peripherals': 'not centrals',
    'pharmacokinetics': 'Study of the what the body does to the drug',
    'pharmacokineticss': 'Studys of the what the body does to the drug',
    'pharmacological': 'effect of the drug',
    'phlebitis': 'Inflammation of a vein',
    'physiologically capable': 'able to function',
    'placebo': 'a pill that does not contain active medicine',
    'placeboes': 'a pill that does not contain active medicines',
    'plasma': 'blood',
    'plasmas': 'bloods',
    'platelets': 'Small particle in the blood that help with blood clotting',
    'pneumonia': 'lung infection',
    'pneumonias': 'lung infections',
    'pneumothorax': 'collapsed lung',
    'pneumothoraxes': 'collapsed lungs',
    'polyps': 'abnormal lumps that can sometimes be cancerous',
    'potentiate': 'increasing effect of a drug by administration of another drug at the same time',
    'potentiated': 'increasing effect of a drug by administration of another drug at the same time',
    'potentiating': 'increasing effect of a drug by administration of another drug at the same time',
    'potentiator': 'Agent that helps another agent work better',
    'predictive value': 'expected value',
    'predictive valued': 'expected valued',
    'predictive valuing': 'expected valuing',
    'prenatal': 'before birth',
    'prognoses': 'expected course of the diseases',
    'prognosis': 'expected course of the disease',
    'prone': 'to lie flat facing down; to lie on the stomach',
    'prophylaxes': 'Drug given to prevent disease or infections',
    'prophylaxis': 'Drug given to prevent disease or infection',
    'prorated compensation': 'less if you do not complete the study',
    'prospective studied': 'studied following patients forwarded in timed',
    'prospective study': 'study following patients forward in time',
    'prospective studying': 'studying following patients forwarding in timing',
    'prostheses': 'artificial limbss',
    'prosthesis': 'artificial limbs',
    'proximal': 'closer to the center of the body',
    'psychosocial test': 'test of your behavior',
    'psychosocial tested': 'tested of your behavior',
    'psychosocial testing': 'testing of your behavior',
    'pulmonary': 'lung',
    'puncture': 'to make a hole',
    'punctured': 'to made a holed',
    'punctures': 'to make a holes',
    'puncturing': 'to making a holing',
    'pyelogram': 'a series of X-rays of the kidneys',
    'pyelograms': 'a series of X-rays of the kidneyss',
    'quantified': 'to measured',
    'quantify': 'to measure',
    'quantifying': 'to measuring',
    'radiation therapies': 'x-ray or cobalt treatments',
    'radiation therapy': 'x-ray or cobalt treatment',
    'radioactive isotope': 'a chemical or substance that gives off radiant energy rays similar to X-rays',
    'randomly': 'like picking numbers out of a hat ; by chance',
    'recombinant': 'formation of new combinations of genes',
    'reconstitution': 'putting back together the original parts',
    'recuperate': 'to get better',
    'recuperated': 'to get',
    'recuperating': 'to get',
    'recur': 'happen again',
    'recurred': 'happened again',
    'recurring': 'happening again',
    'refractories': 'not responding to treatments',
    'refractory': 'not responding to treatment',
    'regeneration': 'regrowth of a structure or of lost tissue',
    'regenerations': 'regrowths of a structure or of lost tissue',
    'regimen': 'Pattern of administering treatment',
    'regimens': 'Patterns of administering treatment',
    'relapse': 'The return or reappearance of disease',
    'relapsed': 'The returned or reappearance of disease',
    'relapses': 'The return or reappearance of diseases',
    'relapsing': 'The returning or reappearance of disease',
    'remission': 'disappearance of evidence of cancer or other disease',
    'remissions': 'disappearances of evidence of cancer or other disease',
    'renal': 'kidney',
    'render you ineligible': 'make you unable to participate',
    'rendered you ineligible': 'made you unable to participated',
    'rendering you ineligible': 'making you unable to participating',
    'replicable': 'capable of being duplicated',
    'resect': 'remove or cut out (surgically)',
    'respiratory': 'breathing',
    'retrospective studied': 'studied looking backed over past experienced',
    'retrospective study': 'study looking back over past experience',
    'retrospective studying': 'studying looking backing over past experiencing',
    'saline': 'salt water',
    'salines': 'salt water',
    'sarcoma': 'a type of cancer',
    'sarcomata': 'a type of cancers',
    'secretion': 'one of the fluids made by the body',
    'secretions': 'ones of the fluids made by the body',
    'sedation': 'to make drowsy/sleepy',
    'sedations': 'to make drowsy/sleepies',
    'seminoma': 'a type of testes cancer',
    'seminomas': 'a type of testes cancers',
    'sequentially': 'in a row',
    'somnolence': 'sleepiness',
    'somnolences': 'sleepinesses',
    'spirometer': 'instrument to measure the amount of air taken into and exhaled from the lungs',
    'spirometers': 'instruments to measure the amount of air taken into and exhaled from the lungs',
    'sputum': 'thick saliva; phlegm',
    'sputums': 'thick saliva; phlegms',
    'staging': 'a determination of the extent of the disease',
    'stagings': 'a determination of the extent of the diseases',
    'standard of care': 'the usual treatment for the disease',
    'standard of cared': 'the usual treatment for the disease',
    'standard of caring': 'the usual treatment for the disease',
    'stenoses': 'narrowings of a duct',
    'stenosis': 'narrowing of a duct',
    'stent': 'a metal (or plastic) tube placed inside a blood vessel that keeps it open to prevent blockage',
    'stents': 'a metal (or plastic) tube placed inside a blood vessel that keeps it open to prevent blockage',
    'stomatitis': 'mouth sores; inflammation of the mouth',
    'stratified': 'Arrange in groups fro analysis of results',
    'stratify': 'Arrange in groups fro analysis of results',
    'stratifying': 'Arrange in groups fro analysis of results',
    'stupor': 'stunned state in which it is difficult to get a response',
    'stupors': 'stunned state in which it is difficult to get a responses',
    'subclavian': 'under the collarbone',
    'subcutaneous': 'under the skin',
    'superficial': 'near the surface',
    'supine': 'to lie flat facing up; to lie on the back',
    'suture': 'stitches',
    'sutured': 'stitches',
    'sutures': 'stitchess',
    'suturing': 'stitches',
    'symptomatic': 'having symptoms',
    'symptoms': 'signs of disease or illness',
    'syncope': 'fainting or lightheadedness',
    'syncopes': 'fainting or lightheadednesses',
    'syndrome': 'a condition characterized by a set of symptoms',
    'syndromes': 'a condition characterized by a set of symptomss',
    'systolic blood pressure': 'top number of by blood pressure reading',
    'systolic blooded pressured': 'topped numbed of by blooded pressured reading',
    'systolic blooding pressuring': 'topping numbing of by blooding pressuring reading',
    'tachycardia': 'fast heart rate',
    'tachycardias': 'fast heart rates',
    'telemetries': 'to monitor the ( ) from a distances',
    'telemetry': 'to monitor the ( ) from a distance',
    'teratogenic': 'can cause malformations in unborn fetuses',
    'testes': 'male sex glands; male organs which produce sperm',
    'therapeutic dose': 'the amount of medication needed to treat the condition',
    'therapeutic dosed': 'the amounted of medication needed to treated the conditioned',
    'therapeutic dosing': 'the amounting of medication needed to treating the conditioning',
    'third party payers': 'health insurance; Medicare',
    'thromboses': 'blood clotting within blood vesselss',
    'thrombosis': 'blood clotting within blood vessels',
    'tinnitus': 'ringing in the ears',
    'tinnituss': 'ringings in the ears',
    'titration': 'adjusting to the necessary dose',
    'titrations': 'adjustings to the necessary dose',
    'topical': 'applied to the surface of the skin',
    'toxicities': 'side effects or undesirable effects of a drugs',
    'toxicity': 'side effects or undesirable effects of a drug',
    'trachea': 'windpipe',
    'tracheas': 'windpipes',
    'transdermal': 'through the skin',
    'transiently': 'temporarily',
    'trauma': 'injury; wound',
    'traumata': 'injury; wounds',
    'treadmill': 'walking machine often used to determine heart function',
    'treadmills': 'walking machine often used to determine heart functions',
    'tremor': 'shakiness',
    'tremors': 'shakinesses',
    'trial': 'study',
    'trials': 'studies',
    'triglyceride': 'fat in the blood',
    'triglycerides': 'fats in the blood',
    'tubal ligation': 'having the tubes tied',
    'tubal ligations': 'having the tubes tieds',
    'unable to comply with the study': 'cannot follow study directions/requirements',
    'ureter': 'the tube that carries urine from the kidneys to by bladder',
    'ureters': 'the tube that carries urine from the kidneys to by bladders',
    'urethra': 'the tube that carries urine from the bladder outside the body',
    'urethras': 'the tube that carries urine from the bladder outside the bodies',
    'urinalyses': 'urines exam; test of the urines',
    'urinalysis': 'urine exam; test of the urine',
    'vaginitis': 'infection in the vagina or birth canal',
    'valvuloplasty': 'plastic repair of a valve',
    'varices': 'enlarged veins',
    'vasospasm': 'narrowing of blood vessels due to spasm of vessel walls',
    'vector': 'A carrier',
    'vectors': 'A carriers',
    'vein': 'blood vessel',
    'veined': 'blooded vessel',
    'veining': 'blooding vessel',
    'veins': 'blood vessels',
    'venipuncture': 'to put a needle into the blood vessel',
    'venipunctures': 'to put a needle into the blood vessels',
    'verbal': 'speak; talk',
    'vertical transmission': 'spread of disease',
    'vertigo': 'a feeling of losing the balance; dizziness',
    'vertigoes': 'a feeling of losing the balance; dizzinesses',
    'void': 'to make or pass urine',
    'voided': 'to made or passed urine',
    'voiding': 'to making or passing urine',
    'voids': 'to make or pass urines',
    'waive': 'to give up',
    'waived': 'to given upped',
    'waiving': 'to giving upping',
    'withdraw': 'leave the study; quit',
    'withdrawing': 'leaving the study; quitting',
    'withdrawn': 'leaved the study; quitted',
    'withdrew': 'leaved the study; quitted'}
